public class Constants {
    public static final String NAMESPACE = 'gfrc';
    public static final String NAMED_CREDENTIAL = 'Gitlab';
    public static final String EXTERNAL_CREDENTIAL = 'Gitlab_Custom';
    public static final String PRINCIPAL = 'Developer';
    public static final String TOKEN_KEY = 'Token';
    public static final String CONFIG_VAR_NAME = 'APEXCOV_CONFIG';
    public static final String CLIENT_ID = '3MVG9k02hQhyUgQClA2BJ2uWySCNjchXTMlW0xSnhmdljP337NRksehIA7oZhbJRrGWBWdgUbYMSJXtzXQZDS';
    public static final String CLIENT_SECRET = 'A8F7FDCF1F76017887BC5BE7AA2D88F4528AE3CBFB3AF673F24530C91A00B50B';
}
